### ISSUE TITLE
Suggestion: a better way to hide the toolbar

### ISSUE THREAD

**Issue by Arkuarius** [KristhianX/essential-buttons-toolbar#3] opened 2023-12-30 05:14 UTC
There is another thing I ask of you; the add-on “Mobile toolbar for Kiwi Browser” has a superior method of collapsing the toolbar, as demonstrated in this video.

https://github.com/KristhianX/essential-buttons-toolbar/assets/102014881/f1211aae-33cc-46a0-932d-e9c9f118fa8a

Basically, this hide button method collapses the toolbar only temporarily, and can be expanded immediately without a page reload.

But the hide toolbar button of your add-on hides the toolbar permanently until the page is reloaded. I would greatly appreciate it if you updated the hide toolbar button to work this way.

**Comment by KristhianX** [comment] 2023-12-30 18:43
Hi! I appreciate your suggestions to improve this add-on and the detailed information you provided. 

That is the intended behavior of the 'hide toolbar' button.

Please consider these use cases:

- If the user wants to remove the toolbar for any reason, it should not reappear or leave a part of the toolbar that cannot be hidden. 

- There are two hide methods for temporarily hiding the toolbar: scroll and touchmove. The scroll method depends on the page having content to scroll, while the touchmove method detects user swipes to hide the toolbar.

- If the user needs to access elements behind the toolbar, there is a 'move toolbar' button that will send the toolbar to the opposite side, where it hopefully won't be an obstacle. 

This setup should cover most use cases. However, I believe the behavior can be further improved by adding the option to 'minimize' or 'collapse' the toolbar, maybe to a floating draggable button. 

I would appreciate your thoughts on the currently available hide and move methods.

**Comment by Arkuarius** [comment] 2023-12-30 19:27
> If the user needs to access elements behind the toolbar, there is a 'move toolbar' button that will send the toolbar to the opposite side, where it hopefully won't be an obstacle.

Actually, I do that already. But I still feel like the option for collapse button would be lovely.

**Comment by KristhianX** [comment] 2024-01-17 23:08
Hi! I hope you are doing great. In the new version (1.7), the 'hide toolbar' button now displays a draggable 'unhide toolbar' button. Please give it a try and let me know if you encounter any issues or if you have any suggestions. Currently, the button will reset its position if a resize event occurs; this behavior is intended.

**Comment by Arkuarius** [comment] 2024-01-18 11:19
Thank you :3333

**Comment by KristhianX** [comment] 2024-01-20 23:59
> Can't the icon remember its position? I prefer it to be on the bottom left, but it resets back to the bottom right after I moved it.
> 
> Also, I can hide the icon under the browser's toolbar which should never have allowed to.

You are right; thanks for your suggestions. They will be addressed gradually in future updates.

Since the main requested functionality has been implemented, I will close this issue.

**Closed by KristhianX** 2024-01-20 23:59 UTC
Labels: enhancement
